name: Daily China Briefing

on:
  workflow_dispatch:
  schedule:
    - cron: '0 5 * * *' # täglich um 06:00 UTC

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write # Ermöglicht Schreibrechte für das Repository
      actions: read  # Standard-Berechtigung für Actions

    steps:
      - name: Repository klonen
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Python installieren
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Abhängigkeiten installieren
        run: |
          python -m pip install --upgrade pip
          pip install feedparser requests beautifulsoup4 lxml

      - name: Briefing-Skript ausführen
        run: python briefing.py
        env:
          CONFIG: ${{ secrets.CONFIG }}
          SUBSTACK_MAIL: ${{ secrets.SUBSTACK_MAIL }}

      - name: cpr_cache.json Inhalt prüfen (vor Commit)
        run: |
          echo "Inhalt von cpr_cache.json vor dem Commit:"
          cat cpr_cache.json || echo "Datei cpr_cache.json existiert nicht"
        continue-on-error: true

      - name: Änderungen an cpr_cache.json committen und pushen
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add cpr_cache.json
          git commit -m "Update cpr_cache.json with latest CPR value" || echo "Keine Änderungen zu committen"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: cpr_cache.json Inhalt prüfen (nach Commit)
        run: |
          echo "Inhalt von cpr_cache.json nach dem Commit:"
          cat cpr_cache.json || echo "Datei cpr_cache.json existiert nicht"
        continue-on-error: true
