name: Daily China Briefing

on:
  workflow_dispatch:
  schedule:
    - cron: '0 5 * * *' # Täglich um 06:00 UTC (07:00 CEST)

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      actions: write

    steps:
      - name: Repository klonen
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Python installieren
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Abhängigkeiten installieren
        run: |
          python -m pip install --upgrade pip
          pip install beautifulsoup4

      - name: Verzeichnis WCI erstellen
        run: |
          mkdir -p WCI
        continue-on-error: true

      - name: Test-WCI-Skript ausführen
        run: python test_wci_email.py
        env:
          DREWRY: ${{ secrets.DREWRY }}
          CONFIG: ${{ secrets.CONFIG }}

      - name: wci_test_log.txt Inhalt prüfen
        run: |
          echo "Inhalt von wci_test_log.txt:"
          cat wci_test_log.txt || echo "Datei wci_test_log.txt existiert nicht"
        continue-on-error: true

      - name: wci_email_*.html Inhalt prüfen
        run: |
          echo "Inhalt von wci_email_*.html:"
          cat wci_email_*.html || echo "Datei wci_email_*.html existiert nicht"
        continue-on-error: true

      - name: daily_briefing.md Inhalt prüfen
        run: |
          echo "Inhalt von daily_briefing.md:"
          cat daily_briefing.md || echo "Datei daily_briefing.md existiert nicht"
        continue-on-error: true

      - name: wci_cache.json Inhalt prüfen
        run: |
          echo "Inhalt von WCI/wci_cache.json:"
          cat WCI/wci_cache.json || echo "Datei WCI/wci_cache.json existiert nicht"
        continue-on-error: true

      - name: Commit and push changes
        run: |
          git config --global user.email "github-actions@github.com"
          git config --global user.name "GitHub Actions"
          git add WCI/wci_cache.json wci_email_*.html daily_briefing.md wci_test_log.txt || echo "No files to add"
          git commit -m "Update WCI cache and briefing" || echo "Nothing to commit"
          git push origin main
        continue-on-error: true
