name: Daily China Briefing

on:
  workflow_dispatch: # Für manuelles Auslösen über "Actions" → "Run Workflow"
  schedule:
    - cron: '0 5 * * *' # Täglich um 06:00 UTC (07:00 CEST)

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Repository klonen
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Python installieren
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Abhängigkeiten installieren
        run: |
          python -m pip install --upgrade pip
          pip install beautifulsoup4

      - name: Verzeichnis freight_indicies erstellen
        run: |
          mkdir -p freight_indicies

      - name: Test-WCI/IACI-Skript ausführen
        run: python test_wci_email.py
        env:
          DREWRY: ${{ secrets.DREWRY }}
          CONFIG: ${{ secrets.CONFIG }}

      - name: Commit and push changes
        run: |
          git config --global user.email "github-actions@github.com"
          git config --global user.name "GitHub Actions"
          git add daily_briefing.md freight_indicies/wci_cache.json freight_indicies/iaci_cache.json
          git commit -m "Update WCI/IACI cache and briefing" || echo "Nothing to commit"
          git pull --rebase origin main || echo "Pull failed, continuing"
          git push origin main || echo "Push failed"
        continue-on-error: true
