name: Daily China Briefing

on:
  workflow_dispatch:
  schedule:
    - cron: '0 5 * * *' # täglich um 06:00 UTC

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write # Ermöglicht Schreibrechte für das Repository
      actions: read  # Standard-Berechtigung für Actions

    steps:
      - name: Repository klonen
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Python installieren
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Abhängigkeiten installieren
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then
            pip install -r requirements.txt
          else
            pip install feedparser requests beautifulsoup4 lxml google-api-python-client pandas pdfplumber
          fi

      - name: Briefing-Skript ausführen
        run: python briefing.py
        env:
          CONFIG: ${{ secrets.CONFIG }}
          SUBSTACK_MAIL: ${{ secrets.SUBSTACK_MAIL }}
          YOUTUBE_API_KEY: ${{ secrets.YOUTUBE_API_KEY }}

      - name: Cache-Dateien Inhalt prüfen (vor Commit)
        run: |
          echo "Inhalt von cpr_cache.json vor dem Commit:"
          cat cpr_cache.json || echo "Datei cpr_cache.json existiert nicht"
          echo "Inhalt von freight_indices_cache.json vor dem Commit:"
          cat freight_indices_cache.json || echo "Datei freight_indices_cache.json existiert nicht"
        continue-on-error: true

      - name: Änderungen an Cache-Dateien committen und pushen
        run: |
          git config --local user.email "action@gmx.com"
          git config --local user.name "GitHub Action"
          git add cpr_cache.json freight_indices_cache.json || echo "Eine oder beide Cache-Dateien fehlen, fahre fort"
          git commit -m "Update cache files with latest CPR and freight indices" || echo "Keine Änderungen zu committen"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Cache-Dateien Inhalt prüfen (nach Commit)
        run: |
          echo "Inhalt von cpr_cache.json nach dem Commit:"
          cat cpr_cache.json || echo "Datei cpr_cache.json existiert nicht"
          echo "Inhalt von freight_indices_cache.json nach dem Commit:"
          cat freight_indices_cache.json || echo "Datei freight_indices_cache.json existiert nicht"
        continue-on-error: true
