name: Daily China Briefing

on:
  workflow_dispatch:
  schedule:
    - cron: '0 5 * * *' # Täglich um 06:00 UTC (07:00 CEST)

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write # Ermöglicht Schreibrechte für das Repository
      actions: read  # Standard-Berechtigung für Actions

    steps:
      - name: Repository klonen
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Python installieren
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Abhängigkeiten installieren
        run: |
          python -m pip install --upgrade pip
          pip install beautifulsoup4

      - name: Test-WCI-Skript ausführen
        run: python test_wci_email.py
        env:
          DREWRY: ${{ secrets.DREWRY }}

      - name: wci_test_log.txt Inhalt prüfen
        run: |
          echo "Inhalt von wci_test_log.txt:"
          cat wci_test_log.txt || echo "Datei wci_test_log.txt existiert nicht"
        continue-on-error: true

      - name: wci_email_*.html Inhalt prüfen
        run: |
          echo "Inhalt von wci_email_*.html:"
          cat wci_email_*.html || echo "Datei wci_email_*.html existiert nicht"
        continue-on-error: true

      - name: daily_briefing.md Inhalt prüfen
        run: |
          echo "Inhalt von daily_briefing.md:"
          cat daily_briefing.md || echo "Datei daily_briefing.md existiert nicht"
        continue-on-error: true

      - name: Änderungen an Ausgabedateien committen und pushen
        run: |
          git config --local user.email "action@gmx.com"
          git config --local user.name "GitHub Action"
          git add wci_test_log.txt wci_email_*.html daily_briefing.md
          git commit -m "Update wci_test_log.txt, wci_email_*.html, and daily_briefing.md with latest values" || echo "Keine Änderungen zu committen"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
