name: Daily China Briefing

on:
  workflow_dispatch:
  schedule:
    - cron: '0 5 * * *' # täglich um 06:00 UTC (07:00 CEST)

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write # Ermöglicht Schreibrechte für das Repository
      actions: read  # Standard-Berechtigung für Actions

    steps:
      - name: Repository klonen
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Python installieren
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Abhängigkeiten installieren
        run: |
          python -m pip install --upgrade pip
          pip install feedparser requests beautifulsoup4 lxml google-api-python-client pandas

      - name: Verzeichnis freight_indicies erstellen
        run: |
          mkdir -p freight_indicies

      - name: Briefing-Skript ausführen
        run: python briefing.py
        env:
          CONFIG: ${{ secrets.CONFIG }}
          SUBSTACK_MAIL: ${{ secrets.SUBSTACK_MAIL }}
          YOUTUBE_API_KEY: ${{ secrets.YOUTUBE_API_KEY }}
          DREWRY: ${{ secrets.DREWRY }}

      - name: cpr_cache.json Inhalt prüfen (vor Commit)
        run: |
          echo "Inhalt von cpr_cache.json vor dem Commit:"
          cat cpr_cache.json || echo "Datei cpr_cache.json existiert nicht"
        continue-on-error: true

      - name: scfi_cache.json Inhalt prüfen (vor Commit)
        run: |
          echo "Inhalt von scfi_cache.json vor dem Commit:"
          cat scfi_cache.json || echo "Datei scfi_cache.json existiert nicht"
        continue-on-error: true

      - name: wci_cache.json Inhalt prüfen (vor Commit)
        run: |
          echo "Inhalt von wci_cache.json vor dem Commit:"
          cat freight_indicies/wci_cache.json || echo "Datei wci_cache.json existiert nicht"
        continue-on-error: true

      - name: iaci_cache.json Inhalt prüfen (vor Commit)
        run: |
          echo "Inhalt von iaci_cache.json vor dem Commit:"
          cat freight_indicies/iaci_cache.json || echo "Datei iaci_cache.json existiert nicht"
        continue-on-error: true

      - name: Änderungen an Cache-Dateien und Briefing committen und pushen
        run: |
          git config --global user.email "github-actions@github.com"
          git config --global user.name "GitHub Actions"
          git add cpr_cache.json scfi_cache.json freight_indicies/wci_cache.json freight_indicies/iaci_cache.json daily_briefing.md
          git commit -m "Update cache files and briefing" || echo "Keine Änderungen zu committen"
          git pull --rebase origin main || echo "Pull failed, continuing"
          git push origin main || echo "Push failed"
        continue-on-error: true

      - name: cpr_cache.json Inhalt prüfen (nach Commit)
        run: |
          echo "Inhalt von cpr_cache.json nach dem Commit:"
          cat cpr_cache.json || echo "Datei cpr_cache.json existiert nicht"
        continue-on-error: true

      - name: scfi_cache.json Inhalt prüfen (nach Commit)
        run: |
          echo "Inhalt von scfi_cache.json nach dem Commit:"
          cat scfi_cache.json || echo "Datei scfi_cache.json existiert nicht"
        continue-on-error: true

      - name: wci_cache.json Inhalt prüfen (nach Commit)
        run: |
          echo "Inhalt von wci_cache.json nach dem Commit:"
          cat freight_indicies/wci_cache.json || echo "Datei wci_cache.json existiert nicht"
        continue-on-error: true

      - name: iaci_cache.json Inhalt prüfen (nach Commit)
        run: |
          echo "Inhalt von iaci_cache.json nach dem Commit:"
          cat freight_indicies/iaci_cache.json || echo "Datei iaci_cache.json existiert nicht"
        continue-on-error: true
