name: Daily China Briefing

on:
  workflow_dispatch:
  schedule:
    - cron: '0 5 * * *' # täglich um 06:00 UTC

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write # Ermöglicht Schreibrechte für das Repository
      actions: read  # Standard-Berechtigung für Actions

    steps:
      - name: Repository klonen
        uses: actions/checkout@v4 # Aktualisiert auf v4 für bessere Kompatibilität
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Python installieren
        uses: actions/setup-python@v5 # Aktualisiert auf v5
        with:
          python-version: '3.10'

      - name: Abhängigkeiten installieren
        run: |
          python -m pip install --upgrade pip
          pip install feedparser requests beautifulsoup4 lxml google-api-python-client pandas

      - name: Briefing-Skript ausführen
        run: python briefing.py
        env:
          CONFIG: ${{ secrets.CONFIG }}
          SUBSTACK_MAIL: ${{ secrets.SUBSTACK_MAIL }}
          YOUTUBE_API_KEY: ${{ secrets.YOUTUBE_API_KEY }}
          DREWRY: ${{ secrets.DREWRY }} # Neues Secret für WCI-E-Mail-Zugang

      - name: cpr_cache.json Inhalt prüfen (vor Commit)
        run: |
          echo "Inhalt von cpr_cache.json vor dem Commit:"
          cat cpr_cache.json || echo "Datei cpr_cache.json existiert nicht"
        continue-on-error: true

      - name: scfi_cache.json Inhalt prüfen (vor Commit)
        run: |
          echo "Inhalt von scfi_cache.json vor dem Commit:"
          cat scfi_cache.json || echo "Datei scfi_cache.json existiert nicht"
        continue-on-error: true

      - name: wci_cache.json Inhalt prüfen (vor Commit)
        run: |
          echo "Inhalt von wci_cache.json vor dem Commit:"
          cat wci_cache.json || echo "Datei wci_cache.json existiert nicht"
        continue-on-error: true

      - name: Änderungen an Cache-Dateien committen und pushen
        run: |
          git config --local user.email "action@gmx.com"
          git config --local user.name "GitHub Action"
          git add cpr_cache.json scfi_cache.json wci_cache.json
          git commit -m "Update cpr_cache.json, scfi_cache.json, and wci_cache.json with latest values" || echo "Keine Änderungen zu committen"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: cpr_cache.json Inhalt prüfen (nach Commit)
        run: |
          echo "Inhalt von cpr_cache.json nach dem Commit:"
          cat cpr_cache.json || echo "Datei cpr_cache.json existiert nicht"
        continue-on-error: true

      - name: scfi_cache.json Inhalt prüfen (nach Commit)
        run: |
          echo "Inhalt von scfi_cache.json nach dem Commit:"
          cat scfi_cache.json || echo "Datei scfi_cache.json existiert nicht"
        continue-on-error: true

      - name: wci_cache.json Inhalt prüfen (nach Commit)
        run: |
          echo "Inhalt von wci_cache.json nach dem Commit:"
          cat wci_cache.json || echo "Datei wci_cache.json existiert nicht"
        continue-on-error: true
