name: Daily China Briefing

on:
  schedule:
    - cron: '0 8 * * *'  # Läuft täglich um 08:00 UTC
  workflow_dispatch:

jobs:
  run-briefing:
    runs-on: ubuntu-latest

    steps:
      - name: Repository auschecken
        uses: actions/checkout@v3

      - name: Python setzen
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Abhängigkeiten installieren
        run: |
          python -m pip install --upgrade pip
          pip install requests  # beautifulsoup4 entfernt, da nicht genutzt
          
      - name: Briefing-Skript ausführen
        run: python briefing.py
        env:
          CONFIG: ${{ secrets.CONFIG }}
          SUBSTACK_MAIL: ${{ secrets.SUBSTACK_MAIL }}
          SUBSTACK_MAIL_PASSWORD: ${{ secrets.SUBSTACK_MAIL_PASSWORD }}
          YOUTUBE_API_KEY: ${{ secrets.YOUTUBE_API_KEY }}

      - name: Inhalt von scfi_cache.json vor dem Commit anzeigen
        run: |
          echo "Inhalt von scfi_cache.json vor dem Commit:"
          cat scfi_cache.json

      - name: Änderungen committen
        run: |
          git config --local user.email "action@gmx.com"
          git config --local user.name "GitHub Action"
          git add scfi_cache.json
          git commit -m "Update scfi_cache.json with latest SCFI data" || echo "Keine Änderungen zu committen"
          git push

      - name: Inhalt von scfi_cache.json nach dem Commit anzeigen
        run: |
          echo "Inhalt von scfi_cache.json nach dem Commit:"
          cat scfi_cache.json
