name: Daily China Briefing

on:
  schedule:
    - cron: '0 5 * * *'  # Täglich um 06:00 UTC (wie alter Code)
  workflow_dispatch:

jobs:
  run-briefing:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      actions: read

    steps:
      - name: Repository auschecken
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Python setzen
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'  # Wie alter Code

      - name: Abhängigkeiten installieren
        run: |
          python -m pip install --upgrade pip
          pip install requests

      - name: Briefing-Skript ausführen
        run: python briefing.py
        env:
          CONFIG: ${{ secrets.CONFIG }}
          SUBSTACK_MAIL: ${{ secrets.SUBSTACK_MAIL }}
          YOUTUBE_API_KEY: ${{ secrets.YOUTUBE_API_KEY }}

      - name: Inhalt von scfi_cache.json vor dem Commit anzeigen
        run: |
          echo "Inhalt von scfi_cache.json vor dem Commit:"
          cat scfi_cache.json || echo "Datei scfi_cache.json existiert nicht"
        continue-on-error: true

      - name: Änderungen committen
        run: |
          git config --local user.email "action@gmx.com"
          git config --local user.name "GitHub Action"
          if [ -f scfi_cache.json ]; then
            git add scfi_cache.json
            git commit -m "Update scfi_cache.json with latest SCFI data" || echo "Keine Änderungen zu committen"
            git push
          else
            echo "scfi_cache.json nicht vorhanden, überspringe Commit"
          fi
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        continue-on-error: true

      - name: Inhalt von scfi_cache.json nach dem Commit anzeigen
        run: |
          echo "Inhalt von scfi_cache.json nach dem Commit:"
          cat scfi_cache.json || echo "Datei scfi_cache.json existiert nicht"
        continue-on-error: true
