name: Nikkei Test

on:
  schedule:
    # 🚨 DAU-ANMERKUNG: Cron-Ausdruck für Testzwecke auf Mo-Sa um 07:00 UTC (08:00 CEST) erweitert.
    # Später zurücksetzen auf '0 7 * * 1-5' für Mo-Fr, wenn der Test abgeschlossen ist.
    - cron: '0 7 * * 1-6'  # Läuft Mo-Sa um 07:00 UTC (08:00 CEST)
  workflow_dispatch:  # Ermöglicht manuelles Ausführen

jobs:
  nikkei-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests beautifulsoup4 lxml  # lxml hinzugefügt

      - name: Run Nikkei test script
        env:
          SUBSTACK_MAIL: ${{ secrets.SUBSTACK_MAIL }}
        run: python nikkei_test.py
