name: Nikkei Test

on:
  schedule:
    - cron: '0 7 * * 1-5'  # Läuft Mo-Fr um 07:00 UTC (08:00 CEST)
  workflow_dispatch:  # Ermöglicht manuelles Ausführen

jobs:
  nikkei-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests beautifulsoup4

      - name: Run Nikkei test script
        env:
          SUBSTACK_MAIL: ${{ secrets.SUBSTACK_MAIL }}
        run: python nikkei_test.py
