name: Think Tank Test

on:
  workflow_dispatch:
  schedule:
    - cron: '0 7 * * *' # täglich um 07:00 UTC (08:00 CEST)

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write # Ermöglicht Schreibrechte für das Repository
      actions: read  # Standard-Berechtigung für Actions

    steps:
      - name: Repository klonen
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Python installieren
        uses: actions/setup-python@v5
        with:
          python-version: '3.11' # Konsistent mit deiner Haupt-.yml

      - name: Abhängigkeiten installieren
        run: |
          python -m pip install --upgrade pip
          pip install imaplib2 beautifulsoup4 lxml requests # Nur benötigte Bibliotheken für E-Mail-Suche

      - name: Verzeichnis main/daily-china-briefing-test erstellen
        run: |
          mkdir -p main/daily-china-briefing-test

      - name: Think Tank Testskript ausführen
        run: python thinktanks.py
        env:
          SUBSTACK_MAIL: ${{ secrets.SUBSTACK_MAIL }}

      - name: thinktanks_briefing.md Inhalt prüfen (vor Commit)
        run: |
          echo "Inhalt von main/daily-china-briefing-test/thinktanks_briefing.md vor dem Commit:"
          cat main/daily-china-briefing-test/thinktanks_briefing.md || echo "Datei thinktanks_briefing.md existiert nicht"
        continue-on-error: true

      - name: Änderungen an thinktanks_briefing.md committen und pushen
        run: |
          git config --global user.email "github-actions@github.com"
          git config --global user.name "GitHub Actions"
          git add main/daily-china-briefing-test/thinktanks_briefing.md
          git commit -m "Update thinktanks_briefing.md with MERICS email test" || echo "Keine Änderungen zu committen"
          git pull --rebase origin main || echo "Pull failed, continuing"
          git push origin main || echo "Push failed"
        continue-on-error: true

      - name: thinktanks_briefing.md Inhalt prüfen (nach Commit)
        run: |
          echo "Inhalt von main/daily-china-briefing-test/thinktanks_briefing.md nach dem Commit:"
          cat main/daily-china-briefing-test/thinktanks_briefing.md || echo "Datei thinktanks_briefing.md existiert nicht"
        continue-on-error: true
